# Justin Ventura's makefile for cleaning.

# ----------------------------------------
# If you don't know what this is for, do
# not worry :)
# ----------------------------------------
# Ventura Academy YT Computer Science
# -> github.com/jventura1738/VACS_YouTube
# ----------------------------------------

# Makefile variables:
binaries = *.o run
gc = g++ -c -std=c++11
go = g++ -o run

# ----------------------------------------
# Commands...

clean:
	rm -rf $(binaries)